services:
  emscripten:
    image: emscripten/emsdk
    container_name: emscripten-c
    volumes:
      - ../srcs/game:/src
      - ../srcs/frontend/game:/build
    networks:
      - transcendence
    entrypoint: ["make", "wasm"]

  db:
    image: postgres
    container_name: postgre-c
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres-v:/var/lib/postgresql
    networks:
      - transcendence

  nginx:
    image: nginx
    container_name: nginx-c
    restart: always
    ports:
      - 8080:80
      - 8443:443
    env_file:
      - .env
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certs:/etc/nginx/certs
    networks:
      - transcendence
    depends_on:
      - emscripten

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-c
    restart: always
    ports:
      - 5050:80
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
    secrets:
      - pgadmin_password
    networks:
      - transcendence
    depends_on:
      - db

secrets:
  db_password:
    file: ./secrets/db_password.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt

volumes:
  postgres-v:

networks:
  transcendence:
    driver: bridge