services:
  postgres:
    image: postgres:18.1
    container_name: postgre-c
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres-v:/var/lib/postgresql
      - ./postgre:/docker-entrypoint-initdb.d
    networks:
      - transcendence

  node:
    build:
      context: ../srcs/backend
      dockerfile: Dockerfile
    container_name: node-c
    restart: on-failure
    ports:
      - 5173:5173
    env_file:
      - .env
    secrets:
      - db_password
      - jwt_secret
      - cookie_secret
      - google_secret
    volumes:
      - ../srcs/frontend:/front
    networks:
      - transcendence
    depends_on:
      - postgres

  # node-dev:
  #   image: node:25.2.1
  #   container_name: node-dev-c
  #   restart: on-failure
  #   env_file:
  #     - .env
  #   secrets:
  #     - db_password
  #     - jwt_secret
  #     - cookie_secret
  #     - google_secret
  #   volumes:
  #     - ../srcs/backend:/app
  #   working_dir: /app
  #   entrypoint: ["/app/prisma_entrypoint.sh"]
  #   command: ["sh", "-c", "npm install --legacy-peer-deps && npx prisma generate && npx prisma db seed && sleep infinity"]
  #   networks:
  #     - transcendence
  #   depends_on:
  #     - postgres

  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: pgadmin-c
    restart: on-failure
    ports:
      - 5050:80
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
    secrets:
      - pgadmin_password
    networks:
      - transcendence
    depends_on:
      - postgres

  emscripten:
    image: emscripten/emsdk:4.0.23
    container_name: emscripten-c
    working_dir: /emscripten
    volumes:
      - ../srcs/game/assets:/assets
      - ../srcs/game/emscripten:/emscripten
      - ../srcs/frontend/src/game/build:/emscripten/build
    networks:
      - transcendence
    entrypoint: ["make", "wasm"]

  game-server:
    build:
      context: ../srcs/game/game-server
      dockerfile: Dockerfile
    container_name: game-server-c
    restart: on-failure
    volumes:
      - ../srcs/game/assets:/src/assets
    networks:
      - transcendence

  nginx:
    image: nginx:1.29.4
    container_name: nginx-c
    restart: on-failure
    ports:
      - 8080:80
      - 8443:443
    env_file:
      - .env
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certs:/etc/nginx/certs
    networks:
      - transcendence
    depends_on:
      - emscripten

secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  cookie_secret:
    file: ./secrets/cookie_secret.txt
  google_secret:
    file: ./secrets/google_secret.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt

volumes:
  postgres-v:
  pgadmin_data:

networks:
  transcendence:
    driver: bridge
