services:
  db:
    image: postgres
    container_name: postgre-c
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres-v:/var/lib/postgresql
      - ./postgre:/docker-entrypoint-initdb.d
    networks:
      - transcendence

  node:
    build:
      context: ../srcs/backend
      dockerfile: Dockerfile
    container_name: node-c
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_password
    entrypoint: ["/app/db_entrypoint.sh"]
    command: ["npm", "start"]
    networks:
      - transcendence
    depends_on:
      - db

  node-dev:
    image: node:25.2.1
    container_name: node-dev-c
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_password
    volumes:
      - ../srcs/backend:/app
    working_dir: /app
    entrypoint: ["/app/db_entrypoint.sh"]
    command: ["sh", "-c", "npm install && npx prisma generate && sleep infinity"]
    #entrypoint: ["sh", "-c", "npm install && npx prisma generate && sleep infinity"]
    networks:
      - transcendence
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-c
    restart: on-failure
    ports:
      - 5050:80
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
    secrets:
      - pgadmin_password
    networks:
      - transcendence
    depends_on:
      - db

  emscripten:
    image: emscripten/emsdk
    container_name: emscripten-c
    volumes:
      - ../srcs/game:/src
      - ../srcs/frontend/game:/build
    networks:
      - transcendence
    entrypoint: ["make", "wasm"]

  nginx:
    image: nginx
    container_name: nginx-c
    restart: on-failure
    ports:
      - 8080:80
      - 8443:443
    env_file:
      - .env
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certs:/etc/nginx/certs
    networks:
      - transcendence
    depends_on:
      - emscripten

secrets:
  db_password:
    file: ./secrets/db_password.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt

volumes:
  postgres-v:

networks:
  transcendence:
    driver: bridge